# Generated by Django 5.1.3 on 2024-12-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_flyer_alter_event_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
    ]
