# Generated by Django 5.1.3 on 2024-12-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendance',
            name='amount_of_guests',
            field=models.IntegerField(default=0),
        ),
    ]
