# Generated by Django 5.1.3 on 2024-12-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventattendance_amount_of_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattendance',
            name='amount_of_guests',
        ),
    ]
